import java.util.*;

/*
    396. Rotate Function

    Problem Summary
    We are given an integer array nums of length n.

    Let arrk be the array formed after rotating nums by k positions clockwise.

    We define:
    F(k) = 0 * arrk[0] + 1 * arrk[1] + 2 * arrk[2] + ... + (n - 1) * arrk[n - 1]

    We need to return the maximum value among:
    F(0), F(1), F(2), ... , F(n - 1)


    --------------------------------------------------
    Example
    --------------------------------------------------
    nums = [4, 3, 2, 6]

    Rotations:
    k = 0 -> [4, 3, 2, 6]
    k = 1 -> [6, 4, 3, 2]
    k = 2 -> [2, 6, 4, 3]
    k = 3 -> [3, 2, 6, 4]

    Now compute:
    F(0) = 0*4 + 1*3 + 2*2 + 3*6 = 25
    F(1) = 0*6 + 1*4 + 2*3 + 3*2 = 16
    F(2) = 0*2 + 1*6 + 2*4 + 3*3 = 23
    F(3) = 0*3 + 1*2 + 2*6 + 3*4 = 26

    Answer = 26


    --------------------------------------------------
    Brute Force Idea
    --------------------------------------------------
    For every possible rotation:
    1. Actually rotate the array
    2. Compute the weighted sum again
    3. Keep the maximum

    Why it is slow:
    - One rotation can take O(n)
    - One weighted sum computation also takes O(n)
    - We do this for all n rotations

    Total = O(n^2)

    Since n can be up to 10^5, O(n^2) will give TLE.


    --------------------------------------------------
    Optimal Idea
    --------------------------------------------------
    Instead of recalculating every F(k) from scratch, we derive the next value
    from the previous one.

    Let:
    sum = sum of all elements in nums
    F(0) = 0*nums[0] + 1*nums[1] + ... + (n-1)*nums[n-1]

    Then the key recurrence is:

    F(k + 1) = F(k) + sum - n * nums[n - 1 - k]


    --------------------------------------------------
    Why does this formula work?
    --------------------------------------------------
    After one clockwise rotation:
    - Most elements shift one index to the right
    - So their multiplier increases by 1
    - That contributes +sum overall

    But one special element wraps around:
    - The last element moves to index 0
    - It loses its old contribution pattern
    - That adjustment becomes: -n * wrappedElement

    So:
    F(k + 1) = F(k) + sum - n * wrappedElement

    For the kth transition, the wrapped element is:
    nums[n - 1 - k]


    --------------------------------------------------
    Walkthrough on Example
    --------------------------------------------------
    nums = [4, 3, 2, 6]
    n = 4
    sum = 15

    F(0) = 25

    F(1) = F(0) + sum - 4 * nums[3]
         = 25 + 15 - 24
         = 16

    F(2) = F(1) + sum - 4 * nums[2]
         = 16 + 15 - 8
         = 23

    F(3) = F(2) + sum - 4 * nums[1]
         = 23 + 15 - 12
         = 26

    Maximum = 26


    --------------------------------------------------
    Important Bug to Avoid
    --------------------------------------------------
    We must include F(0) in the answer.

    A common mistake is to only compare the future values generated by the
    recurrence and forget that the initial configuration itself may already
    be the maximum.


    --------------------------------------------------
    Time and Space Complexity
    --------------------------------------------------
    1. Compute sum and F(0) in one pass -> O(n)
    2. Generate all other F(k) values in one more pass -> O(n)

    Total Time: O(n)
    Space: O(1)


    --------------------------------------------------
    Interview Insight
    --------------------------------------------------
    This problem looks like a simulation problem, but the real trick is:
    - Do not physically rotate the array
    - Do not recompute every weighted sum
    - Reuse the previous answer using a recurrence relation

    This is a classic optimization pattern:
    If consecutive states are related, try to derive one from another.
*/

class Solution {
    public int maxRotateFunction(int[] nums) {
        int n = nums.length;
        int sum = 0;
        int f = 0;

        // Compute:
        // 1. Total sum of the array
        // 2. Initial rotation function value F(0)
        for (int i = 0; i < n; i++) {
            sum += nums[i];
            f += i * nums[i];
        }

        // F(0) must be considered because it may itself be the maximum.
        int ans = f;

        /*
            Generate:
            F(1), F(2), ... , F(n - 1)

            Recurrence:
            F(k + 1) = F(k) + sum - n * nums[n - 1 - k]

            We only need n - 1 transitions because F(0) is already known.
        */
        for (int k = 0; k < n - 1; k++) {
            f = f + sum - n * nums[n - 1 - k];
            ans = Math.max(ans, f);
        }

        return ans;
    }
}

/*
    --------------------------------------------------
    Brute Force Version for Learning
    --------------------------------------------------

    class Solution {
        public int maxRotateFunction(int[] nums) {
            int n = nums.length;
            int[] temp = Arrays.copyOf(nums, n);
            int ans = Integer.MIN_VALUE;

            for (int i = 0; i < n; i++) {
                rotate(temp);

                int current = 0;
                for (int j = 0; j < n; j++) {
                    current += j * temp[j];
                }

                ans = Math.max(ans, current);
            }

            return ans;
        }

        private void rotate(int[] temp) {
            if (temp == null || temp.length <= 1) {
                return;
            }

            int last = temp[temp.length - 1];

            for (int i = temp.length - 1; i > 0; i--) {
                temp[i] = temp[i - 1];
            }

            temp[0] = last;
        }
    }


    Note:
    This approach is useful for understanding the rotations directly, but it is
    too slow for the given constraints because it takes O(n^2) time.
*/
